# Site settings
title: Ideum
email: info@ideum.com
description: >
  Ideum provides a full range of exhibit design, Web design, and interactive
  design services to museums, nonprofit organizations, and socially responsible
  companies. We create dynamic interactive experiences for museum and Web
  visitors.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ideum.com" # the base hostname & protocol for your site
twitter_username: ideum
github_username:  ideum

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - s3_website.yml
